name: OpenMaking.is
description: A field guide to open making for designers and makers.
url: http://www.openmaking.is

encoding:     utf-8
timezone:     Europe/London

permalink:    /:categories/:title/

markdown:     kramdown
markdown_ext: md
redcarpet:
  extensions: []

source:       .
include:      []
exclude:      [
                'CNAME', 
                'Gemfile', 
                'Gemfile.lock', 
                'Procfile',
                'README.md', 
                'UNLICENSE'
              ]
destination:  ./_site
